### ISSUE TITLE
[xamarin.forms] Camera not working in android device

### ISSUE THREAD

**Issue by jitendrajadav** [Scandit/barcodescanner-sdk-xamarin-samples#100]
I am not sure why camera is not working my application I am getting bellow camera please check attachment.

![image](https://user-images.githubusercontent.com/1029026/74420887-2c053b00-4e72-11ea-8784-12113978c324.png)

[Please check sample application here](https://github.com/jitendrajadav/ScanditSample.git)

Note : I am not sure where I can put this error message 

Version update 

Microsoft Visual Studio Professional 2019 Preview
Version 16.5.0 Preview 2.0
VisualStudio.16.Preview/16.5.0-pre.2.0+29721.120
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Professional

Visual C++ 2019   00435-60000-00000-AA694
Microsoft Visual C++ 2019

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.5.000.400 (d16-5@4a7a7df)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.5.0.391 (remotes/origin/d16-5@2aeef9a0a)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.5.42 (afa79c5)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.2.0.84 (d16-5/ac3f71f)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: df42020
    Java.Interop: xamarin/java.interop/d16-5@c0cc770
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.28.0@46204c4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

Xamarin.iOS and Xamarin.Mac SDK   13.14.1.17 (d308800)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by petradonka** [comment]
Hey @jitendrajadav,

We'll take a look at your issue as soon as we can.
Could you tell us if you're experiencing the issue only on Xamarin.Android, or also on Xamarin.iOS?

Thanks,
Petra

**Comment by jitendrajadav** [comment]
Thank you @petradonka 
Right now I am checking only Android I haven't check iPhone will check in iPhone soon and update you 
Thank you very much for your quick reply

**Comment by adydecki** [comment]
Hello @jitendrajadav, this is Adrian from engineering team. We quickly looked at your code and noticed that you have android:hardwareAccelerated="false" in your AndroidManifest.xml file. For the camera preview to work correctly we require to use hardware acceleration. When I enabled it in your app the camera preview started to work.

**Comment by jitendrajadav** [comment]
@adydecki Thank you very much problem resolved I had tried all but forgot this flag only thank you for addressing issue
