### ISSUE TITLE
Scandit BarcodePicker doesn't pick new camera permissions

### ISSUE THREAD

**Issue by ufukhawk** [Scandit/barcodescanner-sdk-xamarin-samples#103]
Hello, the barcode scanner gives this error after asking for camera permission. What should I do?

version : Xamarin.Forms 4.8.0.1364
Scandit.BarcodePicker.Unified 5.16.0.10

Manifest File : 

`<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.xxxx.androidv2" android:versionCode="35" android:versionName="3.4">
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.FLASHLIGHT" />
	<uses-permission android:name="android.permission.CAMERA" />
	<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
	<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
	<uses-feature android:name="android.hardware.location" android:required="true" />
	<uses-feature android:name="android.hardware.location.gps" android:required="true" />
	<uses-feature android:name="android.hardware.location.network" android:required="true" />
	<application android:label="xxx xxx" android:icon="@drawable/icon">
		<provider android:name="android.support.v4.content.FileProvider" android:hardwareAccelerated="true" android:authorities="${applicationId}.fileprovider" android:exported="false" android:grantUriPermissions="true">
			<meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/file_paths"></meta-data>
		</provider>
	</application>
	<uses-sdk android:targetSdkVersion="29" android:minSdkVersion="23" />
</manifest>`

AssemblyInfo.cs 

     `[assembly: AssemblyTitle("xxx.Android")]
      [assembly: AssemblyDescription("xxx Sahin")]
      [assembly: AssemblyConfiguration("")]
      [assembly: AssemblyCompany("xx-xx")]
      [assembly: AssemblyProduct("xxx.Android")]
      [assembly: AssemblyCopyright("Copyright ©  xxx")]
      [assembly: AssemblyTrademark("")]
      [assembly: AssemblyCulture("")]
      [assembly: ComVisible(false)]
      [assembly: UsesFeature("android.hardware.location", Required = true)]
      [assembly: UsesFeature("android.hardware.location.gps", Required = true)]
      [assembly: UsesFeature("android.hardware.location.network", Required = true)]
      [assembly: UsesFeature("android.hardware.camera", Required = true)]
      [assembly: UsesFeature("android.hardware.camera.autofocus", Required = true)]

      // Version information for an assembly consists of the following four values:
      //
      //      Major Version
      //      Minor Version 
      //      Build Number
      //      Revision
      //
      // You can specify all the values or you can default the Build and Revision Numbers 
      // by using the '*' as shown below:
      // [assembly: AssemblyVersion("1.0.*")]
      [assembly: AssemblyVersion("1.0.0.0")]
      [assembly: AssemblyFileVersion("1.0.0.0")]

      // Add some common permissions, these can be removed if not needed
      [assembly: UsesPermission(Android.Manifest.Permission.Internet)]
      [assembly: UsesPermission(Android.Manifest.Permission.WriteExternalStorage)]
      [assembly: UsesFeature("android.permission.WRITE_EXTERNAL_STORAGE", Required = true)]
      [assembly: UsesFeature("android.permission.READ_EXTERNAL_STORAGE", Required = true)]
      [assembly: UsesPermission(Android.Manifest.Permission.Camera)]
      [assembly: Application(UsesCleartextTraffic = true)]`

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/30172226/92229999-06de2580-eeb3-11ea-961e-e1af08c05c0a.gif)

**Comment by petradonka** [comment]
Hey @ufukhawk,

Our support team will be the best to help you out with this problem, they know all the ins and outs of camera permission issues. Please reach out to them through support@scandit.com with the same info you shared here.

Cheers,
— Petra

**Comment by ufukhawk** [comment]
Okay,
Please do not turn it off until the problem is resolved.
Thanks.

**Comment by ufukhawk** [comment]
I fixed problem.
