### ISSUE TITLE
Scandit Upgrade "Native linking failed, undefined Objective-C class"

### ISSUE THREAD

**Issue by Engincode** [Scandit/barcodescanner-sdk-xamarin-samples#110]
I want to upgrade Scandit Library from 6.12.1 to 6.13.1.
When I trying to uprage 
Android side is worked.
Bu iOS side many errors occured.

Like these
**Native linking failed, undefined Objective-C class:**

- SDCCombinedViewfinder. The symbol 'OBJC_CLASS$_SDCCombinedViewfinder'
- SDCAimerViewfinder. The symbol 'OBJC_CLASS$_SDCAimerViewfinder'
- SDCZoomSwitchControl. The symbol 'OBJC_CLASS$_SDCZoomSwitchControl'
- SDCBarcodeSelectionSession. The symbol 'OBJC_CLASS$_SDCBarcodeSelectionSession'
- - etc.....

**Comment by ScanditSupport** [comment]
Hi @Engincode 

My apologies for the issues you are experiencing, as I can see you have already created an internal support request, let's continue the conversation there.

**Comment by Engincode** [comment]
Yes. You're right.
