### ISSUE TITLE
Wrong version of package on NuGet

### ISSUE THREAD

**Issue by stephenhauck** [Scandit/barcodescanner-sdk-xamarin-samples#2]
I am trying to use your example but you are referencing a version of the NuGet package that is not on NuGet and the example is NOT working on iOS as is with my trial key.

In the unified example you have the following 
`<package id="Scandit.BarcodePicker.Unified" version="5.2.1.10" targetFramework="portable-net45+win+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarintvos10+xamarinwatchos10+xamarinios10" />`

The only one available on NuGet is ...
`<package id="Scandit.BarcodePicker.Unified" version="5.2.0.10" targetFramework="portable45-net45+win8+wp8" />`

**Comment by swenner** [comment]
We updated the package to 5.2.1. Sorry for the inconvenience.

**Comment by stephenhauck** [comment]
Thank you.

As an FYI, I report an issue with a license failure that has now gone away so it was an issue with the previous release or something got fixed on the back end while waiting for a resolution.
