### ISSUE TITLE
not able to add Scandit.BarcodePicker.Xamarin 5.8.1.10' - Visual studio for Mac

### ISSUE THREAD

**Issue by ankiitbansal** [Scandit/barcodescanner-sdk-xamarin-samples#25]
Hi team,

When we are trying to add scandit.barcodepicker.xamarin into Xamarin iOS Native project getting below error:

Could not install package 'Scandit.BarcodePicker.Xamarin 5.8.1.10'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by adydecki** [comment]
Hi Ankit,
Thank you for your interest in our package. Please note that package 'Scandit.BarcodePicker.Xamarin' is dedicated to platform project in Xamarin which is iOS or Android only. This project contains platform specific implementation of our BarcodePicker. 
From the error message you posted I assume you were trying to add this package into the shared project in Xamarin. Please use `Scandit.BarcodePicker.Unified` package instead.
