### ISSUE TITLE
[Xamarin.forms] ScanOverlay how to show last scan item into label or something like in [XAML]

### ISSUE THREAD

**Issue by jitendrajadav** [Scandit/barcodescanner-sdk-xamarin-samples#29]
Xamarin ScanOverlay how to show last scan item into label or something like and I want Button for go back for some reason. I have scenario where I have to scan continue that time I have to show last scanned item on same ScanOverlay.

Basically I want to design page in XAML I have tried with

`xmlns:scandit="clr-namespace:Scandit.BarcodePicker.Unified;assembly=Scandit.BarcodePicker.Unified"`
                 
    <ContentPage.Content>

        <Grid 
            HorizontalOptions="FillAndExpand" 
            VerticalOptions="FillAndExpand">

            <Grid.RowDefinitions>
                <RowDefinition Height="*"/>
                <RowDefinition Height="Auto"/>
                <RowDefinition Height="Auto"/>
            </Grid.RowDefinitions>

            <scandit:BarcodePicker 
                x:Name="thePicker" />

            <Label
                Grid.Row="1"
                VerticalOptions="End"
                BackgroundColor="Transparent"
                Text="{Binding BottonText,Mode=TwoWay}"/>
            
            <Button
                Grid.Row="2"
                HorizontalOptions="FillAndExpand"
                BackgroundColor="White"
                Command="{Binding DoneCommand}"
                HeightRequest="50"
                VerticalOptions="End"
                Text="Done"/>
        </Grid>
    </ContentPage.Content>
    
</ContentPage>`

Getting error in to ` <scandit:BarcodePicker 
                x:Name="thePicker" />
`

how to solved this?

**Comment by jitendrajadav** [comment]
any update?

**Comment by moritzhartmeier** [comment]
Hi! With our current Unified implementation it is not possible to show anything on top of the scanner and there are no changes planned to this within the next months. We are planning an update to move away from the Service architecture towards providing a view that can be used (and then adding things on top will be trivial) but it is likely not going to be happening before Q1 of 2019.

Until then the only way you can accomplish this is by writing your own view renderer for xamarin forms using the xamarin native components. There already is a merge request in progress for a sample that demonstrates this (#26). Have a look and see how it works, it is mostly missing the android parts still, but should show you all the basic elements needed.

**Comment by jitendrajadav** [comment]
Thank you @moritzhartmeier I am only able to see alert like PFA, and is there any way where we can put label in bottom of page so continues scanning will happen and people will get to know last scan was so and so.

![screenshot_20180814-150300](https://user-images.githubusercontent.com/1029026/44084100-78bced84-9fd3-11e8-8dd1-05c35ebdcc37.png)

**Comment by moritzhartmeier** [comment]
As said, it is not possible to do with the current implementation. The current ScanService will take up the whole screen no matter what (it's and android activity or ios viewcontroller) and doesn't allow a way to put anything on top or the bottom of it. The only way to accomplish this is to use the native components and create your own wrappers for Xamarin.Form until we get to it ourselves beginning of next year

**Comment by jitendrajadav** [comment]
Thank you @moritzhartmeier  very much for more clarification.

**Comment by jitendrajadav** [comment]
@moritzhartmeier this problem is resolved?

**Comment by moritzhartmeier** [comment]
It is resolved in that I clarified that it is not possible with the Unified API and this version of the Xamarin plugin will never support this feature. There is a new plugin coming with 6.0 in 2019 that will support it but it is going to be in a new repository etc.
