### ISSUE TITLE
Barcode Picker OverlayView for Package Scandit.BarcodePicker.Unified

### ISSUE THREAD

**Issue by impathan** [Scandit/barcodescanner-sdk-xamarin-samples#78]
Hello, 

I want to implement batch scanning in my existing app which is developed in Xamarin.Net Standard. When I install the package Scandit.BarcodePicker.Xamarin then it gives me the compatibility issue. So I installed the package of Scandit.BarcodePicker.Unified.

The unified package is not providing the OverlayView feature that I need to implement for batch scanning.

```
// Cast the overlay view to a RelativeLayout.
RelativeLayout overlayView = (RelativeLayout) picker.OverlayView;
// Create your view, this can be a button, image, etc.
View yourView = new View(context);
```

Is there any other way to integrated the batch scanning with Overlay on picker by using the Unified package?

Thanks
Imrankhan

**Comment by moritzhartmeier** [comment]
Hi!

Please refer to the documentation to see all the available functionality: https://docs.scandit.com/stable/xamarin/index.html

If you are using the unified package the features are more limited than with the native ones. You still have access to overlay functionality through https://docs.scandit.com/stable/xamarin/class_scandit_1_1_barcode_picker_1_1_unified_1_1_scan_overlay.html but it is not a view that you can interact with. The entire unified service is only displayable in fullscreen without any custom overlays from you. If you need this functionality in unified, then your only option for now is to implement a view renderer yourself, similar to the extended sample in this repository. I hope this cleared everything up.

**Comment by niravvikani** [comment]
Hello @moritzhartmeier,

Can you please show us a sample of how to implement a custom view renderer of scandit scanoverlay in unified application?

Thanks.

**Comment by moritzhartmeier** [comment]
As I mentioned, please have a look at the extended sample https://github.com/Scandit/barcodescanner-sdk-xamarin-samples/tree/release-5.10/Unified/ExtendedSample
It has a view renderer for the entire picker, including some of the functionality of the overlay.

**Comment by moritzhartmeier** [comment]
The extended sample does not have a one to one copy of this, but it shows you how a view renderer is implemented. With a view renderer, you have a normal view on the unified side that you can resize and can add other custom views on top of. The Done button and the label with what was scanned are simply views that are drawn on top of the scanner's view on the native side, so once you have the view renderer, you can simply draw xamarin.forms views on top of the scanner yourself just as it is done in the native samples.

**Comment by VicHernandez** [comment]
sorry guys, i can not see the example with view renderer in the Extended Example, is there in any special branch?, many thanks

**Comment by ScanditSupport** [comment]
Hi @VicHernandez , 

the latest version of the sample is here 
https://github.com/Scandit/barcodescanner-sdk-xamarin-samples/tree/release-5.16/Unified
but if you share a quick description of what you want to achieve with support @ scandit.com, we can help you with getting the view renderer set up.

Scandit Support

**Comment by VicHernandez** [comment]
Hello, 

Thanks a lot for your quick response,  
what i need is something like this. I want to add an icon in the bottom left of the scan screen, which displays total scanned items.
I have a xamarin forms project with forms implementation and i want to customize the view for both platforms.

Many thanks

![custom screen](https://user-images.githubusercontent.com/40698543/93914598-61a5b880-fccc-11ea-9526-1388f77c374d.png)

**Comment by ScanditSupport** [comment]
Hi @VicHernandez 
we're happy to help. Would you mind sending a request via email to support@scandit.com?
