### ISSUE TITLE
Package Scandit.BarcodePicker.Unified 5.5.0.10 is not compatible with netstandard1.5 (.NETStandard,Version=v1.5).

### ISSUE THREAD

**Issue by navkar** [Scandit/barcodescanner-sdk-xamarin-samples#8]
![vsmac_screenshot](https://user-images.githubusercontent.com/7309326/32235312-5a5f12fc-be1c-11e7-945b-ec60b14e1172.png)

Can someone help me. Have a look at this error. 

Package Scandit.BarcodePicker.Unified 5.5.0.10 is not compatible with netstandard1.5 (.NETStandard,Version=v1.5). Package Scandit.BarcodePicker.Unified 5.5.0.10 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - net (.NETFramework,Version=v0.0)
  - uap10 (UAP,Version=v1.0)
  - win81 (Windows,Version=v8.1)
  - wpa81 (WindowsPhoneApp,Version=v8.1)
  - xamarinios (Xamarin.iOS,Version=v0.0)

Environment: 

=== Visual Studio Community 2017 for Mac ===

Version 7.2 (build 636)
Installation UUID: 7e3d762f-62f3-481a-80e8-73fb90d420c5
Runtime:
	Mono 5.4.1.6 (2017-06/1f4613aa1ac) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 504010006

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.0.0/Sdks
SDK Versions:
	2.0.0
	1.0.1
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.5.6
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 8.0.2.1 (Visual Studio Community)
Android SDK: /Users/navkar/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.1 (API level 25)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 25.0.5
SDK Build Tools Version: 25.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Apple Developer Tools ===

Xcode 9.0.1 (13249)
Build 9A1004

=== Xamarin.iOS ===

Version: 11.2.0.11 (Visual Studio Community)
Hash: 2f8bbec0
Branch: d15-4-xi
Build date: 2017-10-05 20:56:05-0400

=== Xamarin.Mac ===

Version: 3.8.1.0 (Visual Studio Community)

=== Xamarin Inspector ===

Version: 1.3.2
Hash: 461f09a
Branch: 1.3-release
Build date: Tue, 03 Oct 2017 18:26:57 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 702000636
Git revision: b349c8fc0c2e1aab0179917d56eed75eb3a03337
Build date: 2017-10-06 15:20:04-04
Xamarin addins: a8da992c78f7eb65b3cdb3f951c34a30337cab35
Build lane: monodevelop-lion-d15-4

=== Operating System ===

Mac OS X 10.12.6
Darwin 16.7.0 Darwin Kernel Version 16.7.0
    Thu Jun 15 17:36:27 PDT 2017
    root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

**Comment by navkar** [comment]
Yes. It works on .NET Portable. But Portable PCL is kinda outdated. xamarin recommends to use .NET standard.

**Comment by biasmv** [comment]
Thanks, we will see what has to be changed there. I can't make any promises when this will be done. We will get back in touch with you when we know more.

**Comment by navkar** [comment]
Any updates?

**Comment by williamabates** [comment]
Are there any updates with support for .NETStandard?

<img width="780" alt="screen shot 2018-09-29 at 3 59 17 pm" src="https://user-images.githubusercontent.com/1847219/46250024-ec66bc00-c400-11e8-84dd-0b877032c3dc.png">

**Comment by adydecki** [comment]
Hi William, Thank you for your interest in our Xamarin package. Please note that **Scandit.BarcodePicker.Xamarin** is dedicated to platform project in Xamarin which is iOS or Android only. This package contains platform specific implementation of our BarcodePicker.
For your shared project in Xamarin please add **Scandit.BarcodePicker.Unified** which is .NET Standard compatible since version 5.8.1.
