### ISSUE TITLE
Example Crashes on iOS

### ISSUE THREAD

**Issue by tpitman** [Scandit/barcodescanner-sdk-xamarin-samples#85]
I just cloned this repo and without making any changes built it for iOS and ran it. It crashes on the StartScanningAsync method call.

I am running on macOS latest on a 2018 macbook pro with Visual Studio 2019 release version.

I checked out the 5.10 branch so that the nuget packages could be installed. the 5.11 doesn't work because nuget only has 5.10 and earlier.

How do I fix this crashing?

**Comment by moritzhartmeier** [comment]
Hi @tpitman 
We are looking into the issue currently and will get back to you about this crash as soon as we know more.
The issue you had with the 5.11 branch is because we accidentally already bumped the samples to 5.11.3, we undid this and it should work fine again now.

**Comment by fatalaa** [comment]
Thank you for submitting this report. We are investigating the issue.

**Comment by fatalaa** [comment]
@tpitman, could you help us out by pointing out the sample that did crash for you?
