### ISSUE TITLE
Xamarin Form crash [CH Play report]

### ISSUE THREAD

**Issue by trilm208** [Scandit/barcodescanner-sdk-xamarin-samples#88]
Please check this crash report:
android.runtime.JavaProxyThrowable: at Scandit.BarcodePicker.Unified.ScanActivity.ApplySettings () [0x0000d] in <76cafa6288004bfa8ace519a9d43968a>:0
at Scandit.BarcodePicker.Unified.ScanActivity.OnCreate (Android.OS.Bundle bundle) [0x0004a] in <76cafa6288004bfa8ace519a9d43968a>:0
at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <b97f43152f6147d4b0263ec6c038a4f9>:0
at (wrapper dynamic-method) System.Object.3(intptr,intptr,intptr)

 
  at md599183c73f7ed2654bd129e0b483f2e16.ScanActivity.n_onCreate (Native Method)

 
  at md599183c73f7ed2654bd129e0b483f2e16.ScanActivity.onCreate (ScanActivity.java:45)

 
  at android.app.Activity.performCreate (Activity.java:7224)

 
  at android.app.Activity.performCreate (Activity.java:7213)

 
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1272)

 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2926)

 
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3081)

 
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:78)

 
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:108)

 
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:68)

 
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1831)

 
  at android.os.Handler.dispatchMessage (Handler.java:106)

 
  at android.os.Looper.loop (Looper.java:201)

 
  at android.app.ActivityThread.main (ActivityThread.java:6806)

 
  at java.lang.reflect.Method.invoke (Native Method)

 
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:547)

 
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:873)

**Comment by moritzhartmeier** [comment]
Hi @trilm208 
Could you provide us the code that you use to create the barcode picker? Even better would be if you could provide us a sample with which we can reproduce this. The stack trace doesn't tell us very much as is, just that there somehow is a crash when applying the settings.

**Comment by trilm208** [comment]
Sometime crash when use _semaphoreSlim 
//private readonly System.Threading.SemaphoreSlim _semaphoreSlim = new System.Threading.SemaphoreSlim(1, 1);

 private async void BarcodePickerOnDidScan(ScanSession session)
        {
            try
            {
                //
                if (IsBusy==true)
                {
                    return;
                }
                IsBusy = true;
                //await _semaphoreSlim.WaitAsync();
                var valueBarcode = session.NewlyRecognizedCodes.LastOrDefault()?.Data;
                MyDebugger.WriteLog("BarCode: " + valueBarcode);
                await ScanditService.BarcodePicker.StopScanningAsync();
                ScanditService.BarcodePicker.DidScan -= BarcodePickerOnDidScan;
                await Task.Delay(300);
                ResultDB result_checkBarcode;
                Device.BeginInvokeOnMainThread(async () =>
                {                
                    using (Acr.UserDialogs.UserDialogs.Instance.Loading("Đang kiểm tra barcode sản phẩm..."))
                    {
                        result_checkBarcode = await CheckBarcodeDatabase(valueBarcode);
                    }
                    if (result_checkBarcode.message.IsNotEmpty())
                    {
                        await Application.Current.MainPage.DisplayAlert("Chú ý", result_checkBarcode.message, "OK");                      
                    }
                    else
                    {
                        if (result_checkBarcode.returnDS.FirstTable().Rows.Count == 0)
                        {
                            await Task.Delay(100);
                            Device.BeginInvokeOnMainThread(async () =>
                            {
                                var user_pick = await Application.Current.MainPage.DisplayAlert("Barcode mới", "Vui lòng chọn SP thùng hay SP đơn", "SP thùng", "SP lẻ");
                                //var user_pick = await Acr.UserDialogs.UserDialogs.Instance.ConfirmAsync("Vui lòng chọn SP thùng hay SP đơn", "Barcode mới", "SP thùng", "SP lẻ");
                                if (user_pick == true)
                                {
                                    var newProductPage = new NewProductThungPage(valueBarcode, SystemID, Services, tblUoMThung);
                                    Device.BeginInvokeOnMainThread(async () =>
                                    {
                                        await Navigation.PushAsync(newProductPage);
                                    });
                                }
                                else
                                {
                                    var newProductPage = new NewProductPage(valueBarcode, SystemID, Services, tblUoM);
                                    Device.BeginInvokeOnMainThread(async () =>
                                    {
                                        await Navigation.PushAsync(newProductPage);
                                    });
                                }

                            });

                        }
                        else
                        {
                            var productPricePage = new ProductPricePage(valueBarcode, SystemID, Services, result_checkBarcode.returnDS, tblUoM, tblUoMThung);
                            Device.BeginInvokeOnMainThread(async () =>
                            {
                                await Navigation.PushAsync(productPricePage);
                            });
                        }
                    }

                

                });
                session.StopScanning();
                IsBusy = false;
            }
            catch (Exception ex)
            {
                IsBusy = false;
               
            }
            //finally
            //{
            //    _semaphoreSlim.Release();
            //}
        }

**Comment by TomekJurkowski** [comment]
Hey @trilm208, any chance you could provide us with a working sample that we can use to reproduce and properly track the issue? I tried fitting your code snippet into our simple sample, but wasn't able to reproduce the crash after all.
