### ISSUE TITLE
Incorrect Nuget Package Reference for Unified Sample

### ISSUE THREAD

**Issue by Yortw** [Scandit/barcodescanner-sdk-xamarin-samples#89]
Hi,

The current unified sample project appears to reference the Scandit Unified Nuget package version 5.11.5.10 but that version does not exist on nuget.org, the latest published version is 5.11.4.10.
This means the sample does not build or run out of the box.

Also stopping the sample from running out of the box, I am getting linker errors. There is a previous closed issue suggesting this can be fixed by turning off incremental builds (I am still trying this to confirm) but I note the incremental build option appears to still be enabled in the sample project. This is likely to confuse people new to the samples and perhaps should be fixed?

**Comment by Yortw** [comment]
It appears my linker issues were caused by changing the project to support 32 bit architectures. I was hoping to target the 5th gen iPod, but it seems this component is 64 bit only and that device isn't, so that isn't possible.

**Comment by lucatorella** [comment]
Sorry for the version mismatch, that's fixed. The latest version is 5.11.4.10.

I also fixed the issue with incremental builds (https://github.com/Scandit/barcodescanner-sdk-xamarin-samples/pull/90). It should be disabled and it was not in the extended sample. Is this the project you are having issues with?

About the 32bit issue, our native SDK supports 32 bit architectures, I'll check why you can target it in our Xamarin sample.

**Comment by lucatorella** [comment]
I just archived the Extended sample (with ARMv7 + ARM64) and it works for me.

As you can see, the final binary contains armv7 slice:
```
lipo -info /Users/lucatorella/Library/Developer/Xcode/Archives/2019-07-02/ExtendedSample.iOS\ 7-02-19\ 3.19\ PM.xcarchive/Products/Applications/ExtendedSample.iOS.app/ExtendedSample.iOS
Architectures in the fat file: /Users/lucatorella/Library/Developer/Xcode/Archives/2019-07-02/ExtendedSample.iOS 7-02-19 3.19 PM.xcarchive/Products/Applications/ExtendedSample.iOS.app/ExtendedSample.iOS are: armv7 arm64
```

Can you please tell which sample doesn't work for you?

**Comment by Yortw** [comment]
Hi,

Thanks for the response. It was the 'simple unified' sample I was having trouble with (C:\Temp\barcodescanner-sdk-xamarin-samples-release-5.11\Unified\SimpleSample\SimpleSample.sln).

Apologies for the 32 bit issue, I may have made an assumption and got the cause wrong. Using ARMv7 + ARM64 does seem to work for me, but picking any option with *ARMv7s* included fails. With v7s enabled I see errors like this;

![image](https://user-images.githubusercontent.com/6725891/60561868-44c05500-9da9-11e9-90e9-a680a110480a.png)

Works fine if only ARMv7 is included.

**Comment by lucatorella** [comment]
Since a couple of years, our SDK doesn't include the armv7s binary slice. Apple (since Xcode 6) doesn't requires/encourages armv7s. Apparently the use of armv7s only slightly improves performance on devices with the Apple A6 CPU (iPhone 5/5c) and only for floating-point-heavy applications.

From the Apple Forum:
> The reason for including armv7s would be marginal backward compatibility. But the general differences between armv7 and armv7s instruction sets are minor. So if you choose not to include armv7s, the targeted armv7 machine code still runs fine on 32 bit A6 devices, and hardly one will notice performance gap.

Therefore, if you want to target 32 devices, in particular 5th generation iPod Touch (using an A5 CPU), armv7 is more than enough.

**Comment by Yortw** [comment]
Great, thank you! :)
